language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: Ptr3UNVbRfTkcrMaO+YgVCFEcGzc+7i108Nr7ASCynCqWc3WSkFj9G1etPIHiKBoPmh9jw3kz5INYYcyqD2KWnKUiNoRav8ErQG9YEwieTBtiVHSbU7n1bxCxGz88/ARa8wVpzBYqu/KGdcET4Oaz5wDb7kPFwLGlbXjhPrdxBJlN0hthxSa0KyPDnma1ez3udRKY3lj6TR8ZhEBILbxkpRP1TStHSIWHmRW2+Yj7cUpnpAd+0LiVNdNXbFOM6nOrzhYsGOrCsQvp9m4IpX7VrOaJk3Ik2Ci5/MBl4Vw7pRSLSfIVh3hKsEu4FM/ukEA+GzgAHzgikCk0pfR84q3amB5TpoUSn0/9TQ8hGXfnb91icDm2g2VvUod3O1eilU/XalUEfhhTgssB9yQKZlcl8lH0yUGSRAGnXxg6HbBav3bAnFw8aBoxFqJAZDAXXtv2Xh96Hl0M/ftPwAeCmlFlLxSKo9I+YudnEJqj/1uP9o63NeXLRE9loo4Gn6uLClEBMdbI4OS1YKD0cuz1JdwmkdkQStfqn9miK0YskXLyYjlMijR7iou5UITdKDM673tfgcbPKFlJ31dsH2MH4Eq/5+uZyiCgIKF7hiwQb7njBubU7hpjGlsl8MV585Xt0nLiVEBitJqUYeQyRgK0Ym0Ew/qE5z8IPQVUVtjz9cYx6k=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: bDA29m+vUH/47rh+2XH4Z1RAzuT9GoIsmeYlvVxDJi1/rjRiWeK//Bgjw59W83+2Y/Ro/QjyGTCJmbi5y+O2LaX0DpfyR/GYxZtFLLGzDSAkC5TkXg+0jxJ6F0DrYeNy6KDO0bECAEaBMLO941aqECx+97x1Zn6qXLhxxAH5iltQHNTp92atqVxTzk9gCV703mDZ0mSaTAckqpHLBhH9Xp4iWSCyYgf2l8UA1t+PvzpBZQBKELLJcN+cMaAkC4P3FHIJQXj+1HA3FU19sfqQ0eTBZyI3PsA+S98wDC37u3RKlc84GLLcOZJo0k+2cSYxhb5WjjUmxEZFwBd3Ctc/+IY88HYKpDrS7d/QuL2BPcR7sQHPCkrSFZhZrIq7M8tkriHPbmpnQAQ0PfcNFVe9BugQYh43L5XPOXhfXppAJxutSdZxEjQogZ4DVzlRMHZBYbmtgjTLftx7jXOGYK6BJd85EMR4JBg1XRLkhDjXzwrS8EHSBUp4v+byNmaWwjb/Ar1R9UeWOqZ2ERkQirq40HymRcvohmLw4mgJydoPbge/EiGklTit46HGuHDlsJxxG+mIs7ld5HrM2KELBmhkCAnfDleohCpLoZ0qwLMDVdL7rsp1GHULSS9sU0wbNrWO2ohBpATtjzNsFTktDMowFC/ZvJA4SQGh3kO5WlPqVok=
      on_success: never
      on_failure: always
      on_pull_requests: false
